messages:
  joinmessage: true
  join:
    - "&7--------------------------------"
    - ""
    - "&aDevelopment by Millen"
    - "&aWebsite: &fhttps://millen.dev"
    - "&aDiscord: &fhttps://discord.gg/test"
    - "&aGitHub: &fhttps://github.com/milnee"
    - ""
    - "&7--------------------------------"

